apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: virtual-host-ingress-nginx
  namespace: homework
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /index.html
spec:
  rules:
  - host: 'homework.otus'
    http:
      paths:
      - path: /homepage
        pathType: Exact
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
