apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: 'nginx-deployment'
#    app: nginx # This matches the labels from the Deployment
  ports:
  - protocol: TCP
    port: 80 # Port the service exposes
    targetPort: nginxport
