apiVersion: v1
kind: Service
metadata:
  name: nginx-monitoring-service
  namespace: homework
  labels:
    label: nginx-monitoring-service
spec:
  type: ClusterIP
  selector:
    app: nginx-monitoring

  ports:
  - protocol: TCP
    name: nginxport
    port: 80 # Port the service exposes
    targetPort: nginxport
#  - protocol: TCP
#    port: 8080 # Port for nginx metrics the service exposes
#    targetPort: nginxmetricsport
  - protocol: TCP
    name: metrics
    port: 9113 # Port the service exposes
    targetPort: http-metrics
