global:
  name: consul
  image: "mirror.gcr.io/hashicorp/consul:1.15.2"
  imageK8S: "mirror.gcr.io/hashicorp/consul-k8s-control-plane:1.5.4"

server:
  replicas: 3
  bootstrapExpect: 3
  storage: "10Gi"
  storageClass: "yc-network-hdd"

# Эти секции часто дергают дополнительные init-контейнеры, лучше выключить явно
syncCatalog:
  enabled: false

dns:
  enabled: false

connectInject:
  enabled: false

controller:
  enabled: false

client:
  enabled: true
  image: "mirror.gcr.io/hashicorp/consul:1.15.2"